#!/usr/bin/env python3
"""Reference embeddings for the benchmark prompts, from the BEST teacher candidate instead of a photo.

CompBench prompts have no paired photograph, so the projector reward (a cosine to the DINOv2 patch mean
of the caption's real image) has no target. Substitute the best-of-N reference candidate, N chosen by
the category's own official evaluator, generated by data/build_bench_candidates.py at the teacher's own
documented setting (40 steps, cfg 4.5) and scored by scripts/score_bench_candidates.lsf. The reward
then says "match your target image in perceptual space". (Result, docs/bench/: a null -- the target
is a teacher image a student distilling teacher trajectories already resembles.)

Same conventions as data/build_ref_emb.py: image squashed to height x height (bicubic), HF processor,
CLS dropped, patch mean, L2-normalised, stored fp16 keyed by prompt idx.

    python data/build_bench_ref_emb.py --topk 1   # best of 8
"""
from __future__ import annotations

import argparse
import glob
import json
import os
from pathlib import Path

import torch
import torch.nn.functional as F
from PIL import Image


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scores", default="cache/bench/scores",
                    help="per-category scores.json of the REFERENCE candidates (official evaluator)")
    ap.add_argument("--label", default="bench_ref_k40cfg45")
    ap.add_argument("--images", default="cache/bench/images/bench_ref_k40cfg45")
    ap.add_argument("--K", type=int, default=40, help="the step count the reference images were generated at")
    ap.add_argument("--topk", type=int, default=1,
                    help="average the DINO embeddings of the top-k candidates (1 = the argmax image)")
    ap.add_argument("--dino_id", default="facebook/dinov2-base")
    ap.add_argument("--height", type=int, default=512)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--out", default="cache/reward/ref_emb_bench.pt")
    args = ap.parse_args()
    rank = int(os.environ.get("RANK", 0)); world = int(os.environ.get("WORLD_SIZE", 1))
    device = torch.device("cuda")
    from transformers import AutoImageProcessor, AutoModel
    dino = AutoModel.from_pretrained(args.dino_id).to(device).eval()
    proc = AutoImageProcessor.from_pretrained(args.dino_id)

    recs = []
    for f in sorted(glob.glob(f"{args.scores}/{args.label}_s{args.K}_*/scores.json")):
        for r in json.load(open(f))["per_prompt"]:
            recs.append({"idx": int(r["idx"]), "scores": [float(x) for x in r["image_scores"]]})
    assert recs, f"no scores under {args.scores}/{args.label}_s{args.K}_*"
    recs = [r for r in recs if r["idx"] % world == rank]
    print(f"[r{rank}] {len(recs)} prompts, top-{args.topk} of {len(recs[0]['scores'])}", flush=True)
    out, missing = {}, 0
    with torch.no_grad():
        for i in range(0, len(recs), args.batch):
            chunk = recs[i:i + args.batch]
            for r in chunk:
                idx = r["idx"]
                order = sorted(range(len(r["scores"])), key=lambda j: -r["scores"][j])[:args.topk]
                paths = [f"{args.images}/p{idx:05d}/s{args.K}/cand{j}.png" for j in order]
                paths = [p for p in paths if os.path.exists(p)]
                if not paths:
                    missing += 1
                    continue
                imgs = [Image.open(p).convert("RGB").resize((args.height, args.height), Image.BICUBIC) for p in paths]
                px = proc(images=imgs, return_tensors="pt")["pixel_values"].to(device)
                h = dino(pixel_values=px).last_hidden_state[:, 1:].float()
                e = F.normalize(h.mean(1), dim=-1)                      # per image
                out[idx] = F.normalize(e.mean(0), dim=-1).cpu().to(torch.float16)   # top-k mean, renormalised
            if (i // args.batch) % 20 == 0:
                print(f"[r{rank}] {i + len(chunk)}/{len(recs)}", flush=True)
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    dst = args.out if world == 1 else args.out.replace(".pt", f".rank{rank}.pt")
    torch.save(out, dst)
    print(f"[r{rank}] wrote {len(out)} embeddings ({missing} prompts had no image) -> {dst}", flush=True)


if __name__ == "__main__":
    main()
